@port = 3000
@baseUrl = http://localhost:{{port}}
@contentType = application/json

###

# @name createTrip
# @prompt destination
# @prompt owner_name
# @prompt owner_email
POST {{baseUrl}}/trips HTTP/1.1
Content-Type: {{contentType}}

{
    "destination": "{{destination}}",
    "starts_at": "{{$datetime iso8601 1 d}}",
    "ends_at": "{{$datetime iso8601 10 d}}",
    "owner_name": "{{owner_name}}",
    "owner_email": "{{owner_email}}",
    "emails_to_invite": [
        "nicolasalexandre0001@gmail.com",
        "johndoe@acme.com"
    ]
}

###
@tripId = {{createTrip.response.body.$.trip_id}}

# @name updateTrip
# @prompt destination
PUT {{baseUrl}}/trips/{{tripId}} HTTP/1.1
Content-Type: {{contentType}}

{
    "destination": "{{destination}}",
    "starts_at": "{{$datetime iso8601 2 d}}",
    "ends_at": "{{$datetime iso8601 8 d}}"
}

###

# @name getTrip
GET {{baseUrl}}/trips/{{tripId}} HTTP/1.1

###

# @name confirmTrip
GET {{baseUrl}}/trips/{{tripId}}/confirm HTTP/1.1

###

@participantId = {{confirmTrip.response.body.$.participant_ids[0]}}

# @name confirmParticipant
GET {{baseUrl}}/participants/{{participantId}}/confirm HTTP/1.1

###

# @name createActivity
# @prompt title
POST {{baseUrl}}/trips/{{tripId}}/activities HTTP/1.1
Content-Type: {{contentType}}

{
    "title": "{{title}}",
    "occurs_at": "{{$datetime iso8601 2 d}}"
}

###

# @name getActivities
GET {{baseUrl}}/trips/{{tripId}}/activities HTTP/1.1

###

# @name createLink
# @prompt title
POST {{baseUrl}}/trips/{{tripId}}/links HTTP/1.1
Content-Type: {{contentType}}

{
    "title": "{{title}}",
    "url": "https://github.com/parkournick3"
}

###

# @name getLinks
GET {{baseUrl}}/trips/{{tripId}}/links HTTP/1.1

###

# @name getParticipants
GET {{baseUrl}}/trips/{{tripId}}/participants HTTP/1.1

###

# @name getParticipant
GET {{baseUrl}}/participants/{{participantId}} HTTP/1.1

###

# @name createInvite
# @prompt email
POST {{baseUrl}}/trips/{{tripId}}/invites HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "{{email}}"
}